// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmobaData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class WJAccountInfo;
@class WJBattleDetailData;
@class WJBattlePlayerData;
@class WJPlayerInfo;
@class WJRoomInfo;
@class WJZoneInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum WJCMD

/**
 * /////////////////   公共值 枚举定义  //////////////////////////
 * 协议命令字
 **/
typedef GPB_ENUM(WJCMD) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  WJCMD_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  WJCMD_CmdUnknow = 0,
  WJCMD_CmdAppSvrGetGameStatusReq = 4097,
  WJCMD_CmdAppSvrGetGameStatusResp = 4098,
  WJCMD_CmdAppSvrAccountApplyReq = 4099,
  WJCMD_CmdAppSvrAccountApplyResp = 4100,
  WJCMD_CmdAppSvrReportLoginResultReq = 4101,
  WJCMD_CmdAppSvrReportLoginResultResp = 4102,
  WJCMD_CmdAppSvrGetBattleResultReq = 4103,
  WJCMD_CmdAppSvrGetBattleResultResp = 4104,
  WJCMD_CmdSmobaSvrLoginReq = 8193,
  WJCMD_CmdSmobaSvrLoginResp = 8194,
  WJCMD_CmdSmobaSvrProgressReportReq = 8195,
  WJCMD_CmdSmobaSvrCreateRoomReq = 8197,
  WJCMD_CmdSmobaSvrCreateRoomResp = 8198,
  WJCMD_CmdSmobaSvrJoinRoomReq = 8199,
  WJCMD_CmdSmobaSvrJoinRoomResp = 8200,
  WJCMD_CmdSmobaSvrBattleStartReq = 8201,
  WJCMD_CmdSmobaSvrBattleStartResp = 8202,
  WJCMD_CmdSmobaSvrBattleFinishReq = 8209,
  WJCMD_CmdSmobaSvrBattleFinishResp = 8210,
  WJCMD_CmdAppSmobaAccountInfoReq = 12289,
  WJCMD_CmdAppSmobaAccountInfoResp = 12290,
  WJCMD_CmdAppSmobaJoinRoomReq = 12291,
  WJCMD_CmdAppSmobaJoinRoomResp = 12292,
  WJCMD_CmdAppGmReleaseAccountReq = 36865,
  WJCMD_CmdAppGmReleaseAccountResp = 36866,
};

GPBEnumDescriptor *WJCMD_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL WJCMD_IsValidValue(int32_t value);

#pragma mark - Enum WJRetCode

/** 错误码 */
typedef GPB_ENUM(WJRetCode) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  WJRetCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  WJRetCode_RcOk = 0,

  /** 本地登录信息无效 */
  WJRetCode_RcAccountInfoInvail = 1,

  /** 区服无效，无法登陆 */
  WJRetCode_RcZoneInfoInvail = 2,

  /** 当前玩家无法使用该英雄 */
  WJRetCode_RcHeroidInvail = 3,

  /** 房间类型无效 */
  WJRetCode_RcRoomTypeInvail = 4,
};

GPBEnumDescriptor *WJRetCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL WJRetCode_IsValidValue(int32_t value);

#pragma mark - Enum WJGameStatus

/** 游戏进度 */
typedef GPB_ENUM(WJGameStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  WJGameStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 未知状态 */
  WJGameStatus_GameStatusUnknown = 0,

  /** 初始状态 */
  WJGameStatus_GameStatusInit = 1,

  /** 在大厅等待 */
  WJGameStatus_GameStatusInLobby = 2,

  /** 在房间中 */
  WJGameStatus_GameStatusInRoom = 3,

  /** 选择英雄中 */
  WJGameStatus_GameStatusSelectingHero = 4,

  /** 游戏中 */
  WJGameStatus_GameStatusGaming = 5,
};

GPBEnumDescriptor *WJGameStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL WJGameStatus_IsValidValue(int32_t value);

#pragma mark - Enum WJRoomType

/** 房间类型 */
typedef GPB_ENUM(WJRoomType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  WJRoomType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  WJRoomType_RoomTypeUnknow = 0,

  /** 5V5普通王者峡谷 */
  WJRoomType_RoomType5V5WzxgCommon = 1,

  /** 5V5征召王者峡谷 */
  WJRoomType_RoomType5V5WzxgConcscript = 2,

  /** 5V5深渊大乱斗 */
  WJRoomType_RoomType5V5Ffa = 3,

  /** 3V3长平攻防战 */
  WJRoomType_RoomType3V3 = 4,

  /** 1V1墨家机关道 */
  WJRoomType_RoomType1V1 = 5,
};

GPBEnumDescriptor *WJRoomType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL WJRoomType_IsValidValue(int32_t value);

#pragma mark - Enum WJCampSider

/** 阵营类型 */
typedef GPB_ENUM(WJCampSider) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  WJCampSider_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 阵营，未知、傻逼团队 */
  WJCampSider_CampSiderUnknow = 0,

  /** 阵营，蓝方、左侧团队 */
  WJCampSider_CampSiderBlue = 1,

  /** 阵营，红方、右侧团队 */
  WJCampSider_CampSiderRed = 2,
};

GPBEnumDescriptor *WJCampSider_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL WJCampSider_IsValidValue(int32_t value);

#pragma mark - WJSmobaDataRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface WJSmobaDataRoot : GPBRootObject
@end

#pragma mark - WJAccountInfo

typedef GPB_ENUM(WJAccountInfo_FieldNumber) {
  WJAccountInfo_FieldNumber_PlatformType = 1,
  WJAccountInfo_FieldNumber_Openid = 2,
  WJAccountInfo_FieldNumber_AccessToken = 3,
  WJAccountInfo_FieldNumber_PayToken = 4,
  WJAccountInfo_FieldNumber_LaunchFrom = 5,
  WJAccountInfo_FieldNumber_Account = 6,
};

/**
 * /////////////////   基础结构定义  //////////////////////////
 * 本地登录信息
 **/
@interface WJAccountInfo : GPBMessage

/** 账号平台类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *platformType;

/** 腾讯开放平台openid，唯一 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *openid;

/** 登录态 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** 支付态， 暂时忽略 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payToken;

/** 呼起方式, 暂时忽略 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *launchFrom;

/** qq号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *account;

@end

#pragma mark - WJZoneInfo

typedef GPB_ENUM(WJZoneInfo_FieldNumber) {
  WJZoneInfo_FieldNumber_ZoneId = 1,
  WJZoneInfo_FieldNumber_ZoneName = 2,
};

/**
 * 王者游戏区服信息
 **/
@interface WJZoneInfo : GPBMessage

/** 区服Id */
@property(nonatomic, readwrite) uint32_t zoneId;

/** 区服名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *zoneName;

@end

#pragma mark - WJRoomInfo

typedef GPB_ENUM(WJRoomInfo_FieldNumber) {
  WJRoomInfo_FieldNumber_RoomId = 1,
};

/**
 * 房间信息
 **/
@interface WJRoomInfo : GPBMessage

/** 房间Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

@end

#pragma mark - WJPlayerInfo

typedef GPB_ENUM(WJPlayerInfo_FieldNumber) {
  WJPlayerInfo_FieldNumber_PlayerUid = 1,
  WJPlayerInfo_FieldNumber_PlayerName = 2,
  WJPlayerInfo_FieldNumber_PlayerLevel = 3,
};

/**
 * 召唤师资料
 **/
@interface WJPlayerInfo : GPBMessage

/** 召唤师ID */
@property(nonatomic, readwrite) uint64_t playerUid;

/** 召唤师名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *playerName;

/** 召唤师等级 */
@property(nonatomic, readwrite) uint64_t playerLevel;

@end

#pragma mark - WJBattleDetailData

typedef GPB_ENUM(WJBattleDetailData_FieldNumber) {
  WJBattleDetailData_FieldNumber_Score = 1,
  WJBattleDetailData_FieldNumber_TotalCoin = 2,
  WJBattleDetailData_FieldNumber_KillSoldier = 3,
  WJBattleDetailData_FieldNumber_KillMonster = 4,
  WJBattleDetailData_FieldNumber_Kill = 5,
  WJBattleDetailData_FieldNumber_Dead = 6,
  WJBattleDetailData_FieldNumber_Assist = 7,
  WJBattleDetailData_FieldNumber_DoubleKillNum = 8,
  WJBattleDetailData_FieldNumber_SoulLevel = 9,
  WJBattleDetailData_FieldNumber_EquipIdsArray = 10,
};

/**
 * 比赛结果详细数据
 **/
@interface WJBattleDetailData : GPBMessage

/** 本局打分 */
@property(nonatomic, readwrite) uint32_t score;

/** 经济 */
@property(nonatomic, readwrite) uint32_t totalCoin;

/** 击杀士兵数 */
@property(nonatomic, readwrite) uint32_t killSoldier;

/** 击杀野怪数 */
@property(nonatomic, readwrite) uint32_t killMonster;

/** K */
@property(nonatomic, readwrite) uint32_t kill;

/** D */
@property(nonatomic, readwrite) uint32_t dead;

/** A */
@property(nonatomic, readwrite) uint32_t assist;

@property(nonatomic, readwrite) uint32_t doubleKillNum;

/** 英雄等级 */
@property(nonatomic, readwrite) uint32_t soulLevel;

/** 出装顺序 */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *equipIdsArray;
/** The number of items in @c equipIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger equipIdsArray_Count;

@end

#pragma mark - WJBattlePlayerData

typedef GPB_ENUM(WJBattlePlayerData_FieldNumber) {
  WJBattlePlayerData_FieldNumber_PlayerInfo = 1,
  WJBattlePlayerData_FieldNumber_CampSider = 3,
  WJBattlePlayerData_FieldNumber_HeroSkin = 4,
  WJBattlePlayerData_FieldNumber_HeroName = 5,
  WJBattlePlayerData_FieldNumber_BattleDetailData = 6,
};

/**
 * 比赛结果召唤师数据
 **/
@interface WJBattlePlayerData : GPBMessage

/** 召唤师信息 */
@property(nonatomic, readwrite, strong, null_resettable) WJPlayerInfo *playerInfo;
/** Test to see if @c playerInfo has been set. */
@property(nonatomic, readwrite) BOOL hasPlayerInfo;

/** 阵营方，参见CampSider定义 */
@property(nonatomic, readwrite) WJCampSider campSider;

/** 英雄+皮肤 组合唯一Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *heroSkin;

/** 英雄名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *heroName;

/** 比赛数据 */
@property(nonatomic, readwrite, strong, null_resettable) WJBattleDetailData *battleDetailData;
/** Test to see if @c battleDetailData has been set. */
@property(nonatomic, readwrite) BOOL hasBattleDetailData;

@end

/**
 * Fetches the raw value of a @c WJBattlePlayerData's @c campSider property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t WJBattlePlayerData_CampSider_RawValue(WJBattlePlayerData *message);
/**
 * Sets the raw value of an @c WJBattlePlayerData's @c campSider property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetWJBattlePlayerData_CampSider_RawValue(WJBattlePlayerData *message, int32_t value);

#pragma mark - WJAccountInfoReq

/**
 * /////////////////  APP-SMOBA 通信协议  //////////////////////////
 * moba向app请求账号信息
 **/
@interface WJAccountInfoReq : GPBMessage

@end

#pragma mark - WJAccountInfoResp

typedef GPB_ENUM(WJAccountInfoResp_FieldNumber) {
  WJAccountInfoResp_FieldNumber_AccountInfo = 1,
};

@interface WJAccountInfoResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) WJAccountInfo *accountInfo;
/** Test to see if @c accountInfo has been set. */
@property(nonatomic, readwrite) BOOL hasAccountInfo;

@end

#pragma mark - WJJoinRoomSBReq

typedef GPB_ENUM(WJJoinRoomSBReq_FieldNumber) {
  WJJoinRoomSBReq_FieldNumber_RoomId = 1,
};

/**
 * 安卓端使用，moba向app请求加入房间
 **/
@interface WJJoinRoomSBReq : GPBMessage

/** 房间Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

@end

#pragma mark - WJJoinRoomSBResp

@interface WJJoinRoomSBResp : GPBMessage

@end

#pragma mark - WJGetGameStatusReq

/**
 * /////////////////  APP-SERVER 通信协议  //////////////////////////
 * 获取游戏状态
 **/
@interface WJGetGameStatusReq : GPBMessage

@end

#pragma mark - WJGetGameStatusResp

typedef GPB_ENUM(WJGetGameStatusResp_FieldNumber) {
  WJGetGameStatusResp_FieldNumber_GameStatus = 1,
};

@interface WJGetGameStatusResp : GPBMessage

/** 游戏状态 */
@property(nonatomic, readwrite) WJGameStatus gameStatus;

@end

/**
 * Fetches the raw value of a @c WJGetGameStatusResp's @c gameStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t WJGetGameStatusResp_GameStatus_RawValue(WJGetGameStatusResp *message);
/**
 * Sets the raw value of an @c WJGetGameStatusResp's @c gameStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetWJGetGameStatusResp_GameStatus_RawValue(WJGetGameStatusResp *message, int32_t value);

#pragma mark - WJApplyAccountReq

/**
 * 申请账号
 **/
@interface WJApplyAccountReq : GPBMessage

@end

#pragma mark - WJApplyAccountResp

typedef GPB_ENUM(WJApplyAccountResp_FieldNumber) {
  WJApplyAccountResp_FieldNumber_Account = 1,
  WJApplyAccountResp_FieldNumber_Password = 2,
};

@interface WJApplyAccountResp : GPBMessage

/** qq号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *account;

/** qq密码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@end

#pragma mark - WJReportLoginResultReq

typedef GPB_ENUM(WJReportLoginResultReq_FieldNumber) {
  WJReportLoginResultReq_FieldNumber_Account = 1,
  WJReportLoginResultReq_FieldNumber_LoginSucc = 2,
};

/**
 * 上报登录结果
 **/
@interface WJReportLoginResultReq : GPBMessage

/** qq号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *account;

/** 登录结果, 0:失败；1:成功 */
@property(nonatomic, readwrite) uint32_t loginSucc;

@end

#pragma mark - WJReportLoginResultResp

@interface WJReportLoginResultResp : GPBMessage

@end

#pragma mark - WJGetBattleResultReq

typedef GPB_ENUM(WJGetBattleResultReq_FieldNumber) {
  WJGetBattleResultReq_FieldNumber_BattleId = 1,
};

/**
 * 拉取比赛结果
 **/
@interface WJGetBattleResultReq : GPBMessage

/** 战局Id， 暂时忽略 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *battleId;

@end

#pragma mark - WJGetBattleResultResp

typedef GPB_ENUM(WJGetBattleResultResp_FieldNumber) {
  WJGetBattleResultResp_FieldNumber_CampSiderWin = 1,
  WJGetBattleResultResp_FieldNumber_BattlePlayerDataArray = 2,
};

@interface WJGetBattleResultResp : GPBMessage

/** 获胜方，参见CampSider定义 */
@property(nonatomic, readwrite) WJCampSider campSiderWin;

/** 所有召唤师的本局比赛数据 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WJBattlePlayerData*> *battlePlayerDataArray;
/** The number of items in @c battlePlayerDataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger battlePlayerDataArray_Count;

@end

/**
 * Fetches the raw value of a @c WJGetBattleResultResp's @c campSiderWin property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t WJGetBattleResultResp_CampSiderWin_RawValue(WJGetBattleResultResp *message);
/**
 * Sets the raw value of an @c WJGetBattleResultResp's @c campSiderWin property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetWJGetBattleResultResp_CampSiderWin_RawValue(WJGetBattleResultResp *message, int32_t value);

#pragma mark - WJLoginReq

typedef GPB_ENUM(WJLoginReq_FieldNumber) {
  WJLoginReq_FieldNumber_Account = 1,
};

/**
 * /////////////////  SMOBA-SERVER 通信协议  //////////////////////////
 **/
@interface WJLoginReq : GPBMessage

/** qq号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *account;

@end

#pragma mark - WJLoginResp

typedef GPB_ENUM(WJLoginResp_FieldNumber) {
  WJLoginResp_FieldNumber_IosZoneInfo = 1,
  WJLoginResp_FieldNumber_AndroidZoneInfo = 2,
};

@interface WJLoginResp : GPBMessage

/** 区服信息, ios */
@property(nonatomic, readwrite, strong, null_resettable) WJZoneInfo *iosZoneInfo;
/** Test to see if @c iosZoneInfo has been set. */
@property(nonatomic, readwrite) BOOL hasIosZoneInfo;

/** 区服信息, android */
@property(nonatomic, readwrite, strong, null_resettable) WJZoneInfo *androidZoneInfo;
/** Test to see if @c androidZoneInfo has been set. */
@property(nonatomic, readwrite) BOOL hasAndroidZoneInfo;

@end

#pragma mark - WJProgressResportReq

typedef GPB_ENUM(WJProgressResportReq_FieldNumber) {
  WJProgressResportReq_FieldNumber_PlayerInfo = 1,
  WJProgressResportReq_FieldNumber_GameStatus = 2,
};

/**
 * 客户端进度上报
 **/
@interface WJProgressResportReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) WJPlayerInfo *playerInfo;
/** Test to see if @c playerInfo has been set. */
@property(nonatomic, readwrite) BOOL hasPlayerInfo;

@property(nonatomic, readwrite) WJGameStatus gameStatus;

@end

/**
 * Fetches the raw value of a @c WJProgressResportReq's @c gameStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t WJProgressResportReq_GameStatus_RawValue(WJProgressResportReq *message);
/**
 * Sets the raw value of an @c WJProgressResportReq's @c gameStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetWJProgressResportReq_GameStatus_RawValue(WJProgressResportReq *message, int32_t value);

#pragma mark - WJCreateRoomReq

typedef GPB_ENUM(WJCreateRoomReq_FieldNumber) {
  WJCreateRoomReq_FieldNumber_RoomType = 1,
};

/**
 * 通知房主，创建房间
 **/
@interface WJCreateRoomReq : GPBMessage

/** 房间类型， 参见RoomType定义 */
@property(nonatomic, readwrite) WJRoomType roomType;

@end

/**
 * Fetches the raw value of a @c WJCreateRoomReq's @c roomType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t WJCreateRoomReq_RoomType_RawValue(WJCreateRoomReq *message);
/**
 * Sets the raw value of an @c WJCreateRoomReq's @c roomType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetWJCreateRoomReq_RoomType_RawValue(WJCreateRoomReq *message, int32_t value);

#pragma mark - WJCreateRoomResp

typedef GPB_ENUM(WJCreateRoomResp_FieldNumber) {
  WJCreateRoomResp_FieldNumber_RoomInfo = 1,
};

@interface WJCreateRoomResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) WJRoomInfo *roomInfo;
/** Test to see if @c roomInfo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomInfo;

@end

#pragma mark - WJJoinRoomReq

typedef GPB_ENUM(WJJoinRoomReq_FieldNumber) {
  WJJoinRoomReq_FieldNumber_RoomId = 1,
};

/**
 * 通知玩家，加入房间
 **/
@interface WJJoinRoomReq : GPBMessage

/** 房间Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;

@end

#pragma mark - WJJoinRoomResp

@interface WJJoinRoomResp : GPBMessage

@end

#pragma mark - WJBattleStartReq

/**
 * 通知房主，开始比赛
 **/
@interface WJBattleStartReq : GPBMessage

@end

#pragma mark - WJBattleStartResp

@interface WJBattleStartResp : GPBMessage

@end

#pragma mark - WJBattleFinishReq

typedef GPB_ENUM(WJBattleFinishReq_FieldNumber) {
  WJBattleFinishReq_FieldNumber_CampSiderWin = 1,
  WJBattleFinishReq_FieldNumber_BattlePlayerDataArray = 2,
};

/**
 * 比赛结束，上报比赛结果
 **/
@interface WJBattleFinishReq : GPBMessage

/** 获胜方，参见CampSider定义 */
@property(nonatomic, readwrite) WJCampSider campSiderWin;

/** 所有召唤师的本局比赛数据 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WJBattlePlayerData*> *battlePlayerDataArray;
/** The number of items in @c battlePlayerDataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger battlePlayerDataArray_Count;

@end

/**
 * Fetches the raw value of a @c WJBattleFinishReq's @c campSiderWin property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t WJBattleFinishReq_CampSiderWin_RawValue(WJBattleFinishReq *message);
/**
 * Sets the raw value of an @c WJBattleFinishReq's @c campSiderWin property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetWJBattleFinishReq_CampSiderWin_RawValue(WJBattleFinishReq *message, int32_t value);

#pragma mark - WJBattleFinishResp

@interface WJBattleFinishResp : GPBMessage

@end

#pragma mark - WJGMReleaseAccountReq

/**
 * /////////////////  GM指令  //////////////////////////
 * 释放账号， 调试阶段使用
 **/
@interface WJGMReleaseAccountReq : GPBMessage

@end

#pragma mark - WJGMReleaseAccountResp

@interface WJGMReleaseAccountResp : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
